# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
pod 'Google-Mobile-Ads-SDK', '~> 6.12.2'

source 'https://github.com/CocoaPods/Specs.git'

target 'iBodybuilding-Update' do

end

target 'iBodybuilding-UpdateTests' do

end